# -*- coding: utf-8 -*-
"""Seasonal Agriculture Performance Analysis .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PKGh8I4h6-cZ-4xOtOka1mS5u4DnEVjf
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df=pd.read_csv("/seasonal_agriculture_performance_dataset.csv")

print(f"Dataset Shape {df.shape}")

print("\n--- Missing Values Check ---")
print(df.isnull().sum()[df.isnull().sum() > 0])

display(df.head())

df['Rainfall_mm']=df['Rainfall_mm'].fillna(df['Rainfall_mm'].mean())
df['Soil_Moisture_pct']=df['Soil_Moisture_pct'].fillna(df['Soil_Moisture_pct'].mean())
df['Yield_Tonnes_Ha'] = df['Yield_Tonnes_Ha'].fillna(df['Yield_Tonnes_Ha'].mean())

remaining_miss=df.isnull().sum().sum()
print(f"Total missing values remaining: {remaining_miss}")

sns.set_theme(style="whitegrid", palette="muted")
print("Data is clean and ready for analysis!")

eco_metrics = ['Total_Cost_INR', 'Revenue_INR', 'Profit_INR']
seasonal_eco = df.groupby('Season')[eco_metrics].mean().reset_index()
print("--- Average Economic Outcomes by Season ---")
display(seasonal_eco.round(2))

plt.figure(figsize=(10, 6))
sns.barplot(x='Season', y='Profit_INR', data=df, errorbar=None, palette=['#4C72B0', '#55A868', '#C44E52'])
plt.title('Average Agricultural Profit by Season', fontsize=16, fontweight='bold')
plt.ylabel('Profit (INR)', fontsize=12)
plt.xlabel('Season', fontsize=12)
# Add a horizontal line at 0 to highlight financial losses
plt.axhline(0, color='red', linestyle='--', linewidth=1.5)
plt.show()

resource_metrics = ['Water_Used_m3', 'Fertilizer_kg_ha', 'Pesticide_Litre_ha']
seasonal_resources = df.groupby('Season')[resource_metrics].mean().reset_index()

print("--- Average Resource Usage by Season ---")
display(seasonal_resources.round(2))

plt.figure(figsize=(10, 6))
sns.boxplot(x='Season', y='Water_Used_m3', data=df, palette='Blues')
plt.title('Distribution of Water Usage by Season', fontsize=16, fontweight='bold')
plt.ylabel('Water Used (m³)', fontsize=12)
plt.xlabel('Season', fontsize=12)
plt.show()

plt.figure(figsize=(10, 6))
sns.countplot(x='Season', hue='Irrigation_Method', data=df, palette='Set2')
plt.title('Irrigation Methods Chosen per Season', fontsize=16, fontweight='bold')
plt.ylabel('Number of Farms', fontsize=12)
plt.xlabel('Season', fontsize=12)
plt.legend(title='Irrigation Method')
plt.show()

env_metrics = ['Avg_Temperature_C', 'Rainfall_mm', 'Yield_Tonnes_Ha', 'Disease_Pest_Risk_pct']
seasonal_env = df.groupby('Season')[env_metrics].mean().reset_index()

print("--- Environmental Impact on Yield and Risk ---")
display(seasonal_env.round(2))

plt.figure(figsize=(12, 8))
# Select only numeric columns to find correlations
numeric_cols = ['Rainfall_mm', 'Avg_Temperature_C', 'Humidity_pct', 'Soil_Moisture_pct', 'Water_Used_m3', 'Fertilizer_kg_ha', 'Yield_Tonnes_Ha']
correlation_matrix = df[numeric_cols].corr()
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=.5)
plt.title('Correlation Matrix: Environment vs. Crop Yield', fontsize=16, fontweight='bold')
plt.show()

plt.figure(figsize=(10, 6))
sns.scatterplot(x='Rainfall_mm', y='Yield_Tonnes_Ha', hue='Season', data=df, alpha=0.6, palette='deep')
plt.title('Crop Yield based on Rainfall Variations', fontsize=16, fontweight='bold')
plt.ylabel('Yield (Tonnes per Hectare)', fontsize=12)
plt.xlabel('Rainfall (mm)', fontsize=12)
plt.show()

plt.figure(figsize=(14, 7))
sns.barplot(x='Crop', y='Profit_INR', hue='Season', data=df, errorbar=None, palette='pastel')
plt.title('Profitability of Specific Crops Across Seasons', fontsize=16, fontweight='bold')
plt.ylabel('Profit (INR)', fontsize=12)
plt.xlabel('Crop Type', fontsize=12)
plt.axhline(0, color='red', linestyle='--', linewidth=1.5)
plt.xticks(rotation=45)
plt.legend(title='Season')
plt.show()

state_season_profit = df.groupby(['State', 'Season'])['Profit_INR'].mean().unstack()

print("--- Average Profit by State and Season (INR) ---")
display(state_season_profit.round(2))

print("--- Best and Worst Performing Crops by Season ---")
for season in df['Season'].unique():
    season_data = df[df['Season'] == season]
    crop_profits = season_data.groupby('Crop')['Profit_INR'].mean().sort_values()

    best_crop = crop_profits.index[-1]
    best_profit = crop_profits.iloc[-1]

    worst_crop = crop_profits.index[0]
    worst_profit = crop_profits.iloc[0]

    print(f"\nSeason: {season.upper()}")
    print(f"🏆 Best Crop: {best_crop} (Avg Profit: {best_profit:,.0f} INR)")
    print(f"📉 Worst Crop: {worst_crop} (Avg Profit: {worst_profit:,.0f} INR)")

print("--- Resource Efficiency: Profit per Cubic Meter of Water ---")

df['Profit_Per_Water'] = df['Profit_INR'] / df['Water_Used_m3']

water_efficiency = df.groupby('Season')['Profit_Per_Water'].mean()

print(water_efficiency.round(2))